version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # DooD 설정
      - /usr/bin/docker:/usr/bin/docker
      - ~/kkk:/var/jenkins_home/workspace/kkk_local # 호스트의 ~/kkk를 젠킨스 내부로 마운트
